// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Todos$ReactTemplate = require("../types/Todos.bs.js");

var component = ReasonReact.reducerComponent("Todos");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, "Hello from ReasonML");
            }),
          /* initialState */(function () {
              return /* record */[/* todos : [] */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[/* todos : :: */[
                                  action[0],
                                  state[/* todos */0]
                                ]]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[/* todos */Todos$ReactTemplate.removeTodoById(state[/* todos */0], action[0])]]);
                case 2 : 
                    return /* Update */Block.__(0, [/* record */[/* todos */Todos$ReactTemplate.startTodoById(state[/* todos */0], action[0])]]);
                case 3 : 
                    return /* Update */Block.__(0, [/* record */[/* todos */Todos$ReactTemplate.stopTodoById(state[/* todos */0], action[0])]]);
                case 4 : 
                    return /* Update */Block.__(0, [/* record */[/* todos */Todos$ReactTemplate.tickTodoById(state[/* todos */0], action[0])]]);
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
