// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var $$default = ReasonReact.reducerComponent("Todos");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined);
            }),
          /* initialState */(function () {
              return /* record */[/* todos : [] */0];
            }),
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action.tag) {
                var match = state[/* todos */0];
                return /* Update */Block.__(0, [/* record */[/* todos */match ? match[1] : /* [] */0]]);
              } else {
                return /* Update */Block.__(0, [/* record */[/* todos : :: */[
                              action[0],
                              state[/* todos */0]
                            ]]]);
              }
            }),
          /* subscriptions */$$default[/* subscriptions */13],
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
