// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function incSecond(sec) {
  return /* Second */[sec[0] + 1 | 0];
}

function tickTodo(todo) {
  return /* record */[
          /* todoId */todo[/* todoId */0],
          /* description */todo[/* description */1],
          /* status */todo[/* status */2],
          /* cycles */todo[/* cycles */3],
          /* duration */incSecond(todo[/* duration */4])
        ];
}

var $$default = ReasonReact.reducerComponent("Todos");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined);
            }),
          /* initialState */(function () {
              return /* record */[/* todos : [] */0];
            }),
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[/* todos : :: */[
                                  action[0],
                                  state[/* todos */0]
                                ]]]);
                case 1 : 
                    var todoId = action[0];
                    return /* Update */Block.__(0, [/* record */[/* todos */List.filter((function (t) {
                                          return Caml_obj.caml_notequal(t[/* todoId */0], todoId);
                                        }))(state[/* todos */0])]]);
                case 2 : 
                    var todoId$1 = action[0];
                    return /* Update */Block.__(0, [/* record */[/* todos */List.map((function (t) {
                                        if (Caml_obj.caml_equal(t[/* todoId */0], todoId$1)) {
                                          return /* record */[
                                                  /* todoId */t[/* todoId */0],
                                                  /* description */t[/* description */1],
                                                  /* status : Running */1,
                                                  /* cycles */t[/* cycles */3],
                                                  /* duration */t[/* duration */4]
                                                ];
                                        } else {
                                          return t;
                                        }
                                      }), state[/* todos */0])]]);
                case 3 : 
                    var todoId$2 = action[0];
                    return /* Update */Block.__(0, [/* record */[/* todos */List.map((function (t) {
                                        if (Caml_obj.caml_equal(t[/* todoId */0], todoId$2)) {
                                          return /* record */[
                                                  /* todoId */t[/* todoId */0],
                                                  /* description */t[/* description */1],
                                                  /* status : Unfinished */2,
                                                  /* cycles */t[/* cycles */3],
                                                  /* duration */t[/* duration */4]
                                                ];
                                        } else {
                                          return t;
                                        }
                                      }), state[/* todos */0])]]);
                
              }
            }),
          /* subscriptions */$$default[/* subscriptions */13],
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.incSecond = incSecond;
exports.tickTodo = tickTodo;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
